### ISSUE TITLE
运行错误 

### ISSUE THREAD

**Issue by foreseez** [wencolani/TransE#1]
老哥留个邮箱啊   有点错误  希望能请教一下

**Comment by foreseez** [comment]
![2222222](https://user-images.githubusercontent.com/18757695/50537734-b02d2e00-0b9e-11e9-9d75-3893423162f7.png)

**Comment by wencolani** [comment]
FB15k的数据是按照每行h \t t \t r 的形式，但是这里load_triple是要求每行为h \t r \t t的形式，将151行relationid = self.__relation2id[line_list[1]] 改为relationid = self.__relation2id[line_list[2]]即可

**Comment by wencolani** [comment]
152行 tailid = self.__entity2id[line_list[2]] 改为 tailid = self.__entity2id[line_list[1]]

**Comment by kavinduchamiran** [comment]
English version, Change line 151 and 152 of TransE.py to

```
relationid = self.__relation2id[line_list[2]]
tailid = self.__entity2id[line_list[1]]
```
